language: node_js
node_js:
  - "10"
service:
  - postgresql  
cache:
  directories:
    - "node_modules"

before_script:
  - npm install
  - psql -c "create database free_mentors;" -U postgres
script:
  - npm run create-tables
  - npm test
  
after_success:
  - npm run create-tables
  - npm run coveralls