language: node_js
node_js:
  - stable
service:
  - postgresql  
  
before_script:
  - psql -c "create database free_mentors;" -U postgres
script:
  - npm run create-tables
  - npm test
  
after_success:
  - npm run create-tables
  - npm run coveralls