language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"
services:
  - postgresql  

before_script:
  - psql -c "create database test_env ;" -U postgres
script:
  - npm run create-test
  - npm test
  
after_success:
  - npm run create-test
  - npm run coveralls