language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
services:
  - postgresql 
addons:
  postgresql: "9.6" 

install:
  -npm install  

before_script:
  - psql -c "create database free_mentors;" -U postgres
script:
  - npm test
  
after_success:
  - npm run coveralls